source 'git@github.com/CocoaPods/Specs.git'
platform :ios, '8.0'
#inhibit_all_warnings!

def common
    pod 'SDWebImage', '~>3.8'
    pod 'AFNetworking', '~> 3.0'
	pod 'Masonry', '~>1.0.0'
	pod 'FMDB', '~> 2.3'
end

target 'SmartMall' do
    common

end
